title: Keertana Chidambaram # your name (or website title) here
logo: "/images/mugshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Applied Data Fellow at <a href="http://www.iic.uchicago.edu/applied-data-fellowship">International Innovation Corps</a> 
  <br><br>
  Easily excited about ML, algorithms, networks, and neat data visualizations
  <br><br>
  <a href="https://www.linkedin.com/in/keertana-chidambaram-822920211/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
